default: styles/application.scss
contrast: styles/contrast.scss
mastodon-light: styles/mastodon-light.scss

tangerineui: styles/tangerineui.scss
tangerineui-purple: styles/tangerineui-purple.scss
tangerineui-cherry: styles/tangerineui-cherry.scss
tangerineui-lagoon: styles/tangerineui-lagoon.scss

mastodon-bird-contrast: styles/mastodon-bird-ui-contrast.scss
mastodon-bird-light: styles/mastodon-bird-ui-light.scss
mastodon-bird-dark:  styles/mastodon-bird-ui-dark.scss